enum OutgoingAction {
  SET_USERNAME = 'SET_USERNAME',
  GET_ALL_GAMES = 'GET_ALL_GAMES',
  GET_ALL_USERS = 'GET_ALL_USERS',
  CREATE_GAME = 'CREATE_GAME',
  SEND_MESSAGE = 'SEND_MESSAGE',
  LEAVE_GAME = 'LEAVE_GAME',
  START_GAME = 'START_GAME',
}

export default OutgoingAction;
