enum OutgoingAction {
  SET_USERNAME = 'SET_USERNAME',
  GET_ALL_GAMES = 'GET_ALL_GAMES',
  GET_ALL_USERS = 'GET_ALL_USERS',
  CREATE_GAME = 'CREATE_GAME',
  SEND_MESSAGE = 'SEND_MESSAGE',
  LEAVE_GAME = 'LEAVE_GAME',
  START_GAME = 'START_GAME',
  JOIN_GAME = 'JOIN_GAME',
  GAME_PAGE_LOAD = 'GAME_PAGE_LOAD',
  DRAW_TILE = 'DRAW_TILE',
  PLAY_TILE = 'PLAY_TILE',
  PLAYED_TILE_INTERACTION = 'PLAYED_TILE_INTERACTION',
  SELF_PLAY_TILE = 'SELF_PLAY_TILE',
}

export default OutgoingAction;
