enum OutgoingAction {
  SET_USERNAME = 'SET_USERNAME',
  GET_ALL_GAMES = 'GET_ALL_GAMES',
  GET_ALL_USERS = 'GET_ALL_USERS',
  CREATE_GAME = 'CREATE_GAME',
  SEND_MESSAGE = 'SEND_MESSAGE',
}

export default OutgoingAction;
